server:
  name: user_service  # 服务名称
#  address: 127.0.0.1:10001  # 服务地址
  address: 0.0.0.0:10000  # 服务地址


mysql:
  driver: mysql
  host: user-service-db
  port: 3306
  username: root
  password: 123456
  database: tiny_tiktok


etcd:
#  address: 127.0.0.1:2379
  address: etcd:2379
  password: 123456
  username: root

redis:
  address: 127.0.0.1:6379

