server:
  name: social_service  # 服务名称
#  address: 127.0.0.1:10003  # 服务地址
#  address: 0.0.0.0:10003  # 服务地址
  address: social-service:10003  # 服务地址


mysql:
  driver: mysql
  host: mysql
  port: 3306
  username: root
  password: 123456
  database: tiny_tiktok


etcd:
  address: etcd:2379
  username: root
  password: 123456

redis:
  address: redis:6379
  password: 123456