server:
  name: api_router  # 服务名称
  port: :10000
  address: 127.0.0.1:10000  # 服务地址
  jwtSecret: 123456  # jwt密码


mysql:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: tiny_tiktok


etcd:
  address: 127.0.0.1:2379