Name: product.rpc
ListenOn: 0.0.0.0:8080

Etcd:
  Hosts:
  - 192.168.2.130:2379
  Key: product.rpc
  User: root
  Pass: "123456"


Mysql:
  DataSource: root:123456@tcp(192.168.2.130:3306)/test?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 192.168.2.130:6379
    Type: node
    Pass: