version: '3.1'

services:

  videoService:
    image: 192.168.2.130:5000/bingfood:v1
    container_name: bingFoodClient
    volumes:
      - /app/bingfood:/data
    ports:
      - "8088:8088"
    networks:
      - my_net
#    depends_on:
#      - mysql
#      - redis

#  redis:
#    image: redis:6.2.6
#    ports:
#      - "6379:6379"
#    volumes:
#      - /usr/local/redis/redis.conf:/etc/redis/redis.conf
#      - /usr/local/redis/data:/data
#    networks:
#      - my_net
#    command: redis-server /etc/redis/redis.conf
#
#  mysql:
#    image: mysql:5.7
#    container_name: mysql-5.7
#    #使用该参数，container内的root拥有真正的root权限，否则，container内的root只是外部的一个普通用户权限
#    #设置为true，不然数据卷可能挂载不了，启动不起
#    privileged: true
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#      #      MYSQL_USER: root
#      MYSQL_PASS: 1234
#      TZ: Asia/Shanghai
#    command:
#      --wait_timeout=31536000
#      --interactive_timeout=31536000
#      --max_connections=1000
#      --default-authentication-plugin=mysql_native_password
#    volumes:
#      #映射mysql的数据目录到宿主机，保存数据
#      - "/app/mysql/data:/var/lib/mysql"
#      #根据宿主机下的配置文件创建容器
#      - "/app/mysql/conf/my.cnf:/etc/mysql/my.cnf"


  # 相当于一个docker run命令
networks:
  my_net: