// Code generated by goctl. DO NOT EDIT.
// Source: bing.proto

package server

import (
	"context"

	"binggo/zero/zero-study/interceptorDemo/rpc/bing"
	"binggo/zero/zero-study/interceptorDemo/rpc/internal/logic"
	"binggo/zero/zero-study/interceptorDemo/rpc/internal/svc"
)

type BingServer struct {
	svcCtx *svc.ServiceContext
	bing.UnimplementedBingServer
}

func NewBingServer(svcCtx *svc.ServiceContext) *BingServer {
	return &BingServer{
		svcCtx: svcCtx,
	}
}

func (s *BingServer) Work(ctx context.Context, in *bing.Request) (*bing.Response, error) {
	l := logic.NewWorkLogic(ctx, s.svcCtx)
	return l.Work(in)
}
