FROM golang:alpine as builder

WORKDIR /go/src/app
#后面一个.就是工作目录
COPY . .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && go build -o server .

FROM alpine:latest

MAINTAINER "bingguWang@441282413@qq.com"
#设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

#WORKDIR /go/src/app
RUN ls /go/src/app
COPY --from=0 /go/src/app/server ./
COPY --from=0 /go/src/app/config.yaml ./

EXPOSE 8088
ENTRYPOINT ./server
