server:
  name: video_service  # 服务名称
  port: :10002
#  address: 127.0.0.1:10002  # 服务地址
  address: 0.0.0.0:10000  # 服务地址


mysql:
  driver: mysql
  host: user-service-db
  port: 3306
  username: root
  password: 123456
  database: tiny_tiktok


etcd:
#  address: 127.0.0.1:2379
  address: etcd:2379
  password: 123456

oss:
  bucketName: tiny-tiktok
  endpoint: https://oss-cn-chengdu.aliyuncs.com
  accessKeyId: LTAI5t8nzWHJ1tm92ZPUKods
  accessKeySecret: secret

rabbitMQ:
  user: guest
  password: guest
  address: localhost:5672