version: '3.8'
services:
#
#  user-service:
#    image: 192.168.2.130:8111/test/binggu-user_service:0.1.0
#    hostname: user-service
#    depends_on:
#      - mysql
#      - etcd
#      - redis
#    deploy:
#      replicas: 3
#      #      使用 placement 子关键字来指定服务应该运行在哪些节点上。node.hostname 用于约束服务只在指定的节点上运行。
#      placement:
#        constraints:                      # 添加条件约束
#          - node.labels.role == backend
#    ports:
#      - "10001:10001"
#    command: ["./main"]
#    networks:
#      - tiktok
#    volumes:
#      - /var/logDemo/user-service:/var/logDemo/user_service

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2182:2181
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: bitnami/kafka
    container_name: kafka1
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_NUM_PARTITIONS: 3 # 分区个数
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2 # 分区副本数
      KAFKA_CFG_ZOOKEEPER_CONNECT: 192.168.2.130:2182
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.130:9093
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == wbtest1.novalocal ] # Replace with your actual node hostname
    volumes:
      - /data/docker-compose/kafka/broker1/logs:/opt/kafka/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - kfk

  kafka2:
    image: bitnami/kafka
    container_name: kafka2
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 3 # 分区个数
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2 # 分区副本数
      KAFKA_CFG_ZOOKEEPER_CONNECT: 192.168.2.130:2182
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.130:9094
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == wbtest1.novalocal ] # Replace with your actual node hostname
    volumes:
      - /data/docker-compose/kafka/broker1/logs:/opt/kafka/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - kfk


  kafka3:
    image: bitnami/kafka
    container_name: kafka3
    ports:
      - "9095:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_NUM_PARTITIONS: 3 # 分区个数
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2 # 分区副本数
      KAFKA_CFG_ZOOKEEPER_CONNECT: 192.168.0.66:2182
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.66:9095
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == wbtest2.novalocal ] # Replace with your actual node hostname
    volumes:
      - /data/docker-compose/kafka/broker1/logs:/opt/kafka/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - kfk


#
#volumes:
#  etcd_data:
#    driver: local
#  rabbitdata:
#    driver: local
#  rabbitconf:
#    driver: local

networks:
  kfk:
    driver: overlay