package status

// 发货状态枚举
const (
    DELIVER_STATUS_DONT_DELIVER_FLAG = 0
    DELIVER_STATUS_TO_DELIVER_FLAG   = 1
    DELIVER_STATUS_DELIVERED_FLAG    = 2
    DELIVER_STATUS_RECEIVED_FLAG     = 3
)

const (
    DELIVER_STATUS_DONT_DELIVER_DESC = "发货状态：无需发货"
    DELIVER_STATUS_TO_DELIVER_DESC   = "发货状态：待发货"
    DELIVER_STATUS_DELIVERED_DESC    = "发货状态：已发货"
    DELIVER_STATUS_RECEIVERED_DESC   = "发货状态：已签收"
)

// DELIVER_STATUS_DELIVER_MAP 发货状态枚举表
var DELIVER_STATUS_DELIVER_MAP = map[int]string{
    DELIVER_STATUS_DONT_DELIVER_FLAG: DELIVER_STATUS_DONT_DELIVER_DESC,
    DELIVER_STATUS_TO_DELIVER_FLAG:   DELIVER_STATUS_TO_DELIVER_DESC,
    DELIVER_STATUS_DELIVERED_FLAG:    DELIVER_STATUS_DELIVERED_DESC,
    DELIVER_STATUS_RECEIVED_FLAG:     DELIVER_STATUS_RECEIVERED_DESC,
}
