package status

// 订单状态枚举
const (
    ORDER_STATUS_TO_PAY_FLAG     = 0
    ORDER_STATUS_TO_DELIVER_FLAG = 1
    ORDER_STATUS_TO_RECEIVE_FLAG = 2
    ORDER_STATUS_TO_COMMENT_FLAG = 3
)

const (
    ORDER_STATUS_TO_PAY_DESC     = "订单状态：未支付"
    ORDER_STATUS_TO_DELIVER_DESC = "订单状态：待发货"
    ORDER_STATUS_TO_RECEIVE_DESC = "订单状态：待收货"
    ORDER_STATUS_TO_COMMENT_DESC = "订单状态：待评价"
)

// ORDER_STATUS_MAP 订单状态枚举表
var ORDER_STATUS_MAP = map[int]string{
    ORDER_STATUS_TO_PAY_FLAG:     ORDER_STATUS_TO_PAY_DESC,
    ORDER_STATUS_TO_DELIVER_FLAG: ORDER_STATUS_TO_DELIVER_DESC,
    ORDER_STATUS_TO_RECEIVE_FLAG: ORDER_STATUS_TO_RECEIVE_DESC,
    ORDER_STATUS_TO_COMMENT_FLAG: ORDER_STATUS_TO_COMMENT_DESC,
}
